modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://beforebedtime.net/support"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://beforebedtime.net/api/mods/bbtskin/updates.json"
displayURL = "https://beforebedtime.net/"
logoFile = "assets/bbtskin/icon.png"
credits = "BeforeBedtime Network Team"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "bbtlibs"
mandatory = false
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"
